set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'valloric/youcompleteme'
Plugin 'tpope/vim-commentary'
" Plugin 'xolox/vim-misc'
" Plugin 'xolox/vim-easytags'

call vundle#end()            " required
filetype plugin indent on    " required

" 42 Header
let g:user42 = 'alefranc'
let g:mail42 = 'alefranc@student.42.fr'

" Vim Config
" General
set number			" Show line numbers
set linebreak		" Break lines at word (requires Wrap lines)
set showbreak=+++ 	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch		" Highlight matching brace
 
set hlsearch		" Highlight all search results
set smartcase		" Enable smart-case search
set ignorecase		" Always case-insensitive
set incsearch		" Searches for strings incrementally
 
set autoindent		" Auto-indent new lines
set cindent			" Use 'C' style program indenting
set shiftwidth=4	" Number of auto-indent spaces
set smartindent		" Enable smart-indent
set smarttab		" Enable smart-tabs
set tabstop=4		" Number of spaces per Tab

" Advanced
set ruler			" Show row and column ruler information
 
set undolevels=1000				" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour
  
" Generated by VimConfig.com

" STATUS LINE ------------------------------------------------------------ {{{

set statusline=	" Clear status line when vimrc is reloarded
set statusline+=\ %F\ %m\ %y\ %r\ %O " Status line left side
set statusline+=%= " Use a divider to separate left and right side
set statusline+=\ ascii:\ %b\ hex:\ 0x%B 			 " Status line right side
set statusline+=\ %l:%c\ %p%% " Status line right side
set laststatus=2 " Show the status on the second to last line

" }}}


" SOURCES
" https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/
